#ifndef _MACRO_H
#define _MACRO_H

#define EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_ROWS(TYPE, ROWS) \
  EIGEN_STATIC_ASSERT(TYPE::RowsAtCompileTime == ROWS,       \
                      "THIS_METHOD_IS_ONLY_FOR_MATRICES_OF_SPECIFIC_ROWS")

#define EIGEN_STATIC_ASSERT_MATRIX_SPECIFIC_COLS(TYPE, COLS) \
  EIGEN_STATIC_ASSERT(TYPE::ColsAtCompileTime == COLS,       \
                      "THIS_METHOD_IS_ONLY_FOR_MATRICES_OF_SPECIFIC_COLS")

#endif
